version: '3.8'

services:
  server:
    image: testrag-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ollama-data:/usr/share/ollama/.ollama/models
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - rag-network

  ui:
    image: testrag-ui
    build:
      context: .
      dockerfile: Dockerfile.sl
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app
    depends_on:
      - server
    networks:
      - rag-network

volumes:
  ollama-data:

networks:
  rag-network: